#!/bin/bash
export TURSO_DATABASE_URL='libsql://inspired-chase-h4v0k.aws-us-east-1.turso.io'
export TURSO_AUTH_TOKEN='eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NjkxMzM2ODEsImlkIjoiZmU4OTMyZTItNWE3Yi00ZmFmLWIwODItMzk3ODdlYmVmZmVhIiwicmlkIjoiZWI2NGYxNzQtZDM0ZS00MmZiLTlkN2YtZmQyNDI0Yjc5YzczIn0.hl7bGdxR1Rc2Utr8UmIYKfCv9vP61aQhkcekkkBZbEtHUBmS1Tpe0TJtmLv75xzomj_-KJ3ePKeujGRWtWEVDg'

echo "Running seed with configured credentials..."
node seed.js
